version: "1.0"
info:
  model: int-scaffold
packages:
- name: LDS_Commit_1Project
  gitServerName: GH_PN
  gitUrl: https://github.com/pnagar1705/LDS_Commit_1Project
  gitUsername: pnagar1705
  gitBranch: main
